/**
* @syntax <text>
* @description Prints text to the terminal
*/
//sdfAddons
// use \lwr[LETTER] to lowercase letter
// use \upr[LETTER] to uppercase letter
// use \NL to add a new line
output = termAPI.getArguments(line).join(" ")
    .replace('\\lwr[Q]','q')
    .replace('\\lwr[W]','w')
    .replace('\\lwr[E]','e')
    .replace('\\lwr[R]','r')
    .replace('\\lwr[T]','t')
    .replace('\\lwr[Y]','y')
    .replace('\\lwr[U]','u')
    .replace('\\lwr[I]','i')
    .replace('\\lwr[O]','o')
    .replace('\\lwr[P]','p')
    .replace('\\lwr[A]','a')
    .replace('\\lwr[S]','s')
    .replace('\\lwr[D]','d')
    .replace('\\lwr[F]','f')
    .replace('\\lwr[G]','g')
    .replace('\\lwr[H]','h')
    .replace('\\lwr[J]','j')
    .replace('\\lwr[K]','k')
    .replace('\\lwr[L]','l')
    .replace('\\lwr[Z]','z')
    .replace('\\lwr[X]','x')
    .replace('\\lwr[C]','c')
    .replace('\\lwr[V]','v')
    .replace('\\lwr[B]','b')
    .replace('\\lwr[N]','n')
    .replace('\\lwr[M]','m')
    .replace('\\upr[q]','Q')
    .replace('\\upr[w]','W')
    .replace('\\upr[e]','E')
    .replace('\\upr[r]','R')
    .replace('\\upr[t]','T')
    .replace('\\upr[y]','Y')
    .replace('\\upr[u]','U')
    .replace('\\upr[i]','I')
    .replace('\\upr[o]','O')
    .replace('\\upr[p]','P')
    .replace('\\upr[a]','A')
    .replace('\\upr[s]','S')
    .replace('\\upr[d]','D')
    .replace('\\upr[f]','F')
    .replace('\\upr[g]','G')
    .replace('\\upr[h]','H')
    .replace('\\upr[j]','J')
    .replace('\\upr[k]','K')
    .replace('\\upr[l]','L')
    .replace('\\upr[z]','Z')
    .replace('\\upr[x]','X')
    .replace('\\upr[c]','C')
    .replace('\\upr[v]','V')
    .replace('\\upr[b]','B')
    .replace('\\upr[n]','N')
    .replace('\\upr[m]','M')
    .replace("\\NL","\n")
//end lowercase
termAPI.write(output)